### ISSUE TITLE
Increase security for receiving updates

### ISSUE THREAD

**Issue by craftyguy** [craftyguy/esp-bootstrap#3]
Current implementation will only verify integrity of an update received, but not verify authenticity/privileges of the person/device sending the update. This is a HUGE security concern if this project is going to be used on an untrusted network, so for the time being **DO NOT USE THIS PROJECT ON AN UNTRUSTED NETWORK**

Some ideas on how to address this:

- Use the [micropython ussl library](https://docs.micropython.org/en/latest/esp8266/library/ussl.html) to implement a TLS connection, and authenticate using a shared passphrase
  - The current ussl implementation for the esp8266 does NOT verify certificates so a MTM attack is still a thing.

Other ideas are welcome! I'll edit this post with more ideas as they come to me.

**Comment by craftyguy** [comment]
@achton

I just submitted a way to authenticate updates using a preshared passphrase,and would appreciate feedback if you are interested.

**Comment by achton** [comment]
@craftyguy I have tested this a bit, and have had no issues. It seems to work as expected.

(I find that a confirmation message from esp_updater.py would be nice, even moreso in this case where I may be unable to confirm that the device is functioning properly by looking at it. But that is out of scope here.)

**Comment by craftyguy** [comment]
@achton

Thanks for the feedback. I too feel that this seems to be working as expected so I'll close this.

Definitely file a new ticket with more info on the confirmation message (e.g. confirm after update applied, or versioning for updates [bring printed too], or ???) and I'll add it in!
